name: BOT AMP Catalog
description: Internal AMP catalog for BOT

entries:
  - title: Churn Prediction
    label: cml-amp-churn-prediction
    short_description: Customer churn prediction AMP
    long_description: |
      Customer churn prediction Applied Machine Learning Prototype.
    image_path: https://raw.githubusercontent.com/cloudera/CML_AMP_Churn_Prediction/master/images/catalog-entry.png
    tags:
      - Machine Learning
      - Classification
      - Churn
    git_url: https://github.com/cloudera/CML_AMP_Churn_Prediction.git
    is_prototype: true
    is_community: false
    is_new: false
